toc:
  - name: Neos.js Plugin - Commands
    children:
      - neosjs-commands
    description: |
      Plugin Library for [Neos.js](https://www.npmjs.com/package/@bombitmanbomb/neosjs)
  - CommandManager
